### ISSUE TITLE
gradle 打包带不上依赖

### ISSUE THREAD

**Issue by maybe-why-not** [ScriptKid-Beta/Unexpected_information#1]
![image](https://user-images.githubusercontent.com/29968903/95010993-fa8aeb00-065f-11eb-921f-04ebd99da524.png)
想多加一点正则，用gradle4.4或6.6.1打包源代码带不上依赖。求解。

**Comment by ScriptKid-Beta** [comment]
shadowJar 编译可成功编译出可独立运行的jar包（包含第三方依赖）

**Comment by ScriptKid-Beta** [comment]
有什么正则、需求建议，师傅可在这里提出来，欢迎提交~

**Comment by ivybao0628** [comment]
诸如{to:{pathname:"/staff"}  还有一些接口后有空格的{to:{pathname:"/staff/a "}  就匹配不到了

补充了下
["|'](/[0-9a-zA-Z.]).*?["|']|(["|'](/v[1-9].*?)")|(["|'](/api.*?)")

**Comment by ScriptKid-Beta** [comment]
> 诸如{to:{pathname:"/staff"} 还有一些接口后有空格的{to:{pathname:"/staff/a "} 就匹配不到了
> 
> 补充了下
> ["|'](/%5B0-9a-zA-Z.%5D).*?["|']|(["|'](/v%5B1-9%5D.*?)")|(["|'](/api.*?)")

可以具体提供一下需要匹配的场景、链接、内容体等？以及需要实现的具体效果是？
