### ISSUE TITLE
提个需求

### ISSUE THREAD

**Issue by aedoo** [ScriptKid-Beta/Unexpected_information#2]
可以增加匹配URL吗
http://xxx.com/test/test/asdasd
https://xxx.com/test/test/asdasd

**Comment by alixiaowei** [comment]
哪种场景下的URL匹配，有数据包吗？

**Comment by aedoo** [comment]
一般是在JavaScript文件，有时候不仅有接口格式为：/api/get 这种，还有可能有http://.......或者https://........

**Comment by aedoo** [comment]
例如
![image](https://user-images.githubusercontent.com/19517413/98226659-48fa1500-1f91-11eb-8ecc-83c05a8ce8f2.png)

**Comment by ScriptKid-Beta** [comment]
https://github.com/ScriptKid-Beta/Unexpected_information/releases/tag/v2.3已添加你提个需求，有任何问题欢迎反馈~

**Comment by ScriptKid-Beta** [comment]
已添加你提个需求，有任何问题欢迎反馈~
https://github.com/ScriptKid-Beta/Unexpected_information/releases/tag/v2.3
