### ISSUE TITLE
建议其他情况也加高亮

### ISSUE THREAD

**Issue by rainninenine** [ScriptKid-Beta/Unexpected_information#3]
建议此种情况 “其他 -> 无 (只开启Unexpected information标签页)” 也加高亮，大量请求历史中一个个点开看有没有Unexpected information标签页挺繁琐的

**Comment by rainninenine** [comment]
建议灰色

**Comment by ScriptKid-Beta** [comment]
已添加你提个需求，有任何问题欢迎反馈~
https://github.com/ScriptKid-Beta/Unexpected_information/releases/tag/v2.3.1
