### ISSUE TITLE
js过大时分析导致burpsuite无法加载js的响应

### ISSUE THREAD

**Issue by hcjcn** [ScriptKid-Beta/Unexpected_information#4]
webpack打包的项目，js 21M时，js加载一下pending

**Comment by hcjcn** [comment]
JS过大，响应This message is too large to display时会发生这种情况

**Comment by ScriptKid-Beta** [comment]
有相关截图、链接等吗？

**Comment by hcjcn** [comment]
1）未接BurpSuite时（图1），系统访问正常
图1：
![image](https://user-images.githubusercontent.com/3012971/114480304-e8a08b00-9c34-11eb-870e-5826a716ad6f.png)
2）接上BurpSuite+
Unexpected_information时（图2），系统访问异常，js无法加载
图2：
![image](https://user-images.githubusercontent.com/3012971/114481750-c3f9e280-9c37-11eb-8eec-567d1dea6448.png)

3）接上BurpSuite+
不使用Unexpected_information时（图3），系统访问正常
图3：
![image](https://user-images.githubusercontent.com/3012971/114480604-72505880-9c35-11eb-9296-86029a3b646a.png)
4）接上BurpSuite+
不使用Unexpected_information先访问系统，再加载Unexpected_information，在此js响应中点击插件获取分析结果，导致Burpsuite无响应、资源使用异常（图4、5）
图4、5：
![image](https://user-images.githubusercontent.com/3012971/114480908-09b5ab80-9c36-11eb-8214-fee04b7c9c78.png)
![image](https://user-images.githubusercontent.com/3012971/114481034-4da8b080-9c36-11eb-8535-f77e66112f44.png)


图中汉化可忽略，测试系统为内部系统，你可找一个任意有较大响应值（burp响应加载为This message is too large to display）的js在BurpSuite任意版本重现。

**Comment by ScriptKid-Beta** [comment]
经多次测试，是burp suite遇到较大响应包时会出现This message is too large to display，并非插件导致。

**Comment by ScriptKid-Beta** [comment]
Tips: 如果Response提示This message is too large to display，可尝试通过点击Response中的Hex查看，或者点击Response中的Hex再点击Raw可正常加载查看。
