### ISSUE TITLE
使用burp的2107版本可能出现界面错误

### ISSUE THREAD

**Issue by R4ph4e1-0x01** [ScriptKid-Beta/Unexpected_information#5]
![image](https://user-images.githubusercontent.com/50319524/125410498-82700380-e3ef-11eb-9833-58dc127c85c0.png)
访问history->访问插件新建的标签页render->点击切换其他标签页->失去请求响应栏（可能是错位到最左侧拉不回来）

**Comment by ScriptKid-Beta** [comment]
还请师傅详细描述，感觉这个非插件问题导致，而是该burp版本问题吧。
